name: final-project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Docker
        run: |
          docker --version
          docker info
      
      - name: Debug Dockerfile presence
        run: |
          echo "Revisar la presencia del Dockerfile"
          ls ./App

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./App
          file: ./App/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USER }}/${{ vars.IMAGE_NAME }}:${{ vars.IMAGE_TAG }}

  run:
    runs-on: [self-hosted]
    needs: build

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Descargar imagen desde Docker Hub
        run: |
          docker pull ${{ vars.DOCKERHUB_USER }}/${{ vars.IMAGE_NAME }}:${{ vars.IMAGE_TAG }}

      - name: Ejecutar contenedor en segundo plano
        run: |
          docker run -d --name mi-app-container -p 5000:5000 ${{ vars.DOCKERHUB_USER }}/${{ vars.IMAGE_NAME }}:${{ vars.IMAGE_TAG }}

      - name: Esperar que el contenedor esté listo
        run: |
          echo "Esperando 10 segundos para que el contenedor esté listo..."
          sleep 10
 
      - name: Test con curl
        shell: powershell
        run: |
          Write-Host "Probando el endpoint..."
          try {
            $response = Invoke-WebRequest -Uri http://localhost:5500 -UseBasicParsing
            Write-Host "Código de estado: $($response.StatusCode)"
            Write-Host "Encabezados:"
            $response.Headers | ForEach-Object { Write-Host "$($_.Key): $($_.Value)" }
            Write-Host "Contenido:"
            Write-Host $response.Content
            if ($response.StatusCode -ne 200) {
              Write-Host "Error: respuesta HTTP $($response.StatusCode)"
              exit 1
            }
          } catch {
            Write-Host "Falló la solicitud HTTP"
            Write-Host $_.Exception.Message
            exit 1
          }

      - name: Mostrar logs del contenedor (si falla)
        if: failure()
        shell: pwsh
        run: |
          try {
            docker logs mi-app-container
          } catch {
            Write-Output "No se pudo obtener logs"
          }

      - name: Esperar para ver el resultado manual
        run: |
          echo "Esperando 30 segundos para confirmacion manual del container"
          sleep 30

      - name: Parar y eliminar contenedor
        run: |
          docker stop mi-app-container
          docker rm mi-app-container

      - name: Limpiar imágenes y contenedores
        run: |
          docker system prune -af

      
      
      

    
